name: absensi_selfie_lokasi
description: App Absensi Wajah (Web) + Lokasi GPS + Supabase + TensorFlow.js

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.9
  supabase_auth_ui: ^0.4.1
  image_picker: ^1.0.4

  # Lokasi (Web compatible)
  geolocator: ^10.1.0

  # Util
  intl: ^0.18.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
