name: absensi_selfie_lokasi
description: App Absensi Mobile + GPS + Selfie + Supabase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.9
  supabase_auth_ui: ^0.4.1

  # Kamera Mobile
  camera: ^0.10.6

  # Ambil gambar
  image_picker: ^1.0.4

  # GPS
  geolocator: ^10.1.0

  # HTTP
  http: ^1.1.0

  # Format tanggal
  intl: ^0.18.1

  device_info_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true