name: absensi_selfie_lokasi
description: App Absensi Wajah dengan Firebase Firestore - Manual Nama + NPM, Lokasi GPS, Izin/Cuti/Sakit, Riwayat Hapus Swipe.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.9
  supabase_auth_ui: ^0.4.1
  camera: ^0.10.5
  google_mlkit_face_detection: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/

  # No custom fonts needed